export const Tehsils = [
  { value: "Attock", label: "Attock" },
  { value: "FatehJang", label: "Fateh Jang" },
  { value: "HasanAbdal", label: "Hasan Abdal" },
  { value: "Hazro", label: "Hazro" },
  { value: "Jand", label: "Jand" },
  { value: "PindiGheb", label: "Pindi Gheb" },
  { value: "Bahawalnagar", label: "Bahawalnagar" },
  { value: "Chishtian", label: "Chishtian" },
  { value: "FortAbbas", label: "Fort Abbas" },
  { value: "Haroonabad", label: "Haroonabad" },
  { value: "Minchinabad", label: "Minchinabad" },
  { value: "AhmadpurEast", label: "Ahmadpur East" },
  { value: "BahawalpurCity", label: "Bahawalpur City" },
  { value: "Bahawalpur", label: "Bahawalpur" },
  { value: "Hasilpur", label: "Hasilpur" },
  { value: "KhairpurTamewali", label: "Khairpur Tamewali" },
  { value: "Yazman", label: "Yazman" },
  { value: "Bhakkar", label: "Bhakkar" },
  { value: "DaryKhan", label: "Darya Khan" },
  { value: "Kaloorkot", label: "Kaloorkot" },
  { value: "Mankera", label: "Mankera" },
  { value: "Chakwal", label: "Chakwal" },
  { value: "ChoaSaidanShah", label: "Choa Saidan Shah" },
  { value: "KallarKahar", label: "Kallar Kahar" },
  { value: "Lawa", label: "Lawa" },
  { value: "Talagang", label: "Talagang" },
  { value: "Bhawana", label: "Bhawana" },
  { value: "Chiniot", label: "Chiniot" },
  { value: "Lalian", label: "Lalian" },
  { value: "DeraGhaziKhan", label: "Dera Ghazi Khan" },
  { value: " Koh - e - Suleman", label: "Koh-e-Suleman" },
  { value: "KotChutta", label: "Kot Chutta" },
  { value: "Taunsa", label: "Taunsa" },
  { value: "ChakJhumra", label: "Chak Jhumra" },
  { value: "FaisalabadCity", label: "Faisalabad City" },
  { value: "FaisalabadSadar", label: "Faisalabad Sadar" },
  { value: "Jaranwala", label: "Jaranwala" },
  { value: "Samundri", label: "Samundri" },
  { value: "Tandlianwala", label: "Tandlianwala" },
  { value: "GujranwalaCity", label: "Gujranwala City" },
  { value: "GujranwalaSaddar", label: "Gujranwala Saddar" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "NowsheraVirkan", label: "Nowshera Virkan" },
  { value: "Wazirabad", label: "Wazirabad" },
  { value: "Gujrat", label: "Gujrat" },
  { value: "JalalpurJattan", label: "Jalalpur Jattan" },
  { value: "Kharian", label: "Kharian" },
  { value: "SaraiAlamgir", label: "Sarai Alamgir" },
  { value: "Hafizabad", label: "Hafizabad" },
  { value: "PindiBhattian", label: "Pindi Bhattian" },
  { value: "AhmadpurSial", label: "Ahmadpur Sial" },
  { value: "AtharaHazari", label: "Athara Hazari" },
  { value: "Jhang", label: "Jhang" },
  { value: "Shorkot", label: "Shorkot" },
  { value: "Dina", label: "Dina" },
  { value: "Jhelum", label: "Jhelum" },
  { value: "PindDadanKhan", label: "Pind Dadan Khan" },
  { value: "Sohawa", label: "Sohawa" },
  { value: "Chunian", label: "Chunian" },
  { value: "Kasur", label: "Kasur" },
  { value: "KotRadhaKishan", label: "Kot Radha Kishan" },
  { value: "Pattoki", label: "Pattoki" },
  { value: "Jahanian", label: "Jahanian" },
  { value: "Kabirwala", label: "Kabirwala" },
  { value: "Khanewal", label: "Khanewal" },
  { value: "MianChannu", label: "Mian Channu" },
  { value: "Khushab", label: "Khushab" },
  { value: "Naushera", label: "Naushera" },
  { value: "NoorpurThal", label: "Noorpur Thal" },
  { value: "Quaidabad", label: "Quaidabad" },
  { value: "LahoreCantonment", label: "Lahore Cantonment" },
  { value: "LahoreCity", label: "Lahore City" },
  { value: "ModelTown", label: "Model Town" },
  { value: "Raiwind", label: "Raiwind" },
  { value: "Shalimar", label: "Shalimar" },
  { value: "Chaubara", label: "Chaubara" },
  { value: "KarorLalEsan", label: "Karor Lal Esan" },
  { value: "Layyah", label: "Layyah" },
  { value: "Dunyapur", label: "Dunyapur" },
  { value: "KahrorPacca", label: "Kahror Pacca" },
  { value: "Lodhran", label: "Lodhran" },
  { value: "Malikwal", label: "Malikwal" },
  { value: "MandiBahauddin", label: "Mandi Bahauddin" },
  { value: "Phalia", label: "Phalia" },
  { value: "Isakhel", label: "Isakhel" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Piplan", label: "Piplan" },
  { value: "JalalpurPirwala", label: "Jalalpur Pirwala" },
  { value: "MultanCity", label: "Multan City" },
  { value: "MultanSaddar", label: "Multan Saddar" },
  { value: "Shujabad", label: "Shujabad" },
  { value: "Alipur", label: "Alipur" },
  { value: "Jatoi", label: "Jatoi" },
  { value: "KotAddu", label: "Kot Addu" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "NankanaSahib", label: "Nankana Sahib" },
  { value: "SanglaHill", label: "Sangla Hill" },
  { value: "ShahKot", label: "Shah Kot" },
  { value: "Narowal", label: "Narowal" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Zafarwal", label: "Zafarwal" },
  { value: "Depalpur", label: "Depalpur" },
  { value: "Okara", label: "Okara" },
  { value: "RenalaKhurd", label: "Renala Khurd" },
  { value: "Arifwala", label: "Arifwala" },
  { value: "Pakpattan", label: "Pakpattan" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Liaqatpur", label: "Liaqatpur" },
  { value: "RahimYarKhan", label: "Rahim Yar Khan" },
  { value: "Sadiqabad", label: "Sadiqabad" },
  { value: "Jampur", label: "Jampur" },
  { value: "Rajanpur", label: "Rajanpur" },
  { value: "Rojhan", label: "Rojhan" },
  { value: "GujarKhan", label: "Gujar Khan" },
  { value: "Kahuta", label: "Kahuta" },
  { value: "KallarSyedan", label: "Kallar Syedan" },
  { value: "KotliSattian", label: "Kotli Sattian" },
  { value: "Murree", label: "Murree" },
  { value: "Potohar", label: "Potohar" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "Taxila", label: "Taxila" },
  { value: "Chichawatni", label: "Chichawatni" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Bhalwal", label: "Bhalwal" },
  { value: "Bhera", label: "Bhera" },
  { value: "KotMomin", label: "Kot Momin" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Sargodha", label: "Sargodha" },
  { value: "Shahpur", label: "Shahpur" },
  { value: "Sillanwali", label: "Sillanwali" },
  { value: "Ferozewala", label: "Ferozewala" },
  { value: "Muridke", label: "Muridke" },
  { value: "Safdarabad", label: "Safdarabad" },
  { value: "SharakPur", label: "Sharak Pur" },
  { value: "Sheikhupura", label: "Sheikhupura" },
  { value: "Daska", label: "Daska" },
  { value: "Pasrur", label: "Pasrur" },
  { value: "Sambrial", label: "Sambrial" },
  { value: "Sialkot", label: "Sialkot" },
  { value: "Gojra", label: "Gojra" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Pirmahal", label: "Pirmahal" },
  { value: "TobaTekSingh", label: "Toba Tek Singh" },
  { value: "Burewala", label: "Burewala" },
  { value: "Mailsi", label: "Mailsi" },
  { value: "SajjadCSPC", label: "Sajjad CSPC" },
  { value: "Vehari", label: "Vehari" },
];
